 server:
  servlet:
   context-path: /pessoa-endereco/api
   
  spring:
    datasource:
      url: jdbc:h2:men:demodb
      username: sa
      password:
      driverClasseName: org.h2.Driver
       
  h2:
    console:
      enabled: true
      path: /h2-console
